services:
  SumoCoders\FrameworkMultiUserBundle\User\DoctrineBaseUserRepository:
    class: SumoCoders\FrameworkMultiUserBundle\User\DoctrineBaseUserRepository
  multi_user.base_user.repository:
    alias: SumoCoders\FrameworkMultiUserBundle\User\DoctrineBaseUserRepository
