services:
  SumoCoders\FrameworkMultiUserBundle\User\DoctrineBaseUserRepository:
    class: SumoCoders\FrameworkMultiUserBundle\User\DoctrineBaseUserRepository
    arguments:
      - '@doctrine'
    tags: ['doctrine.repository_service']
  multi_user.base_user.repository:
    alias: SumoCoders\FrameworkMultiUserBundle\User\DoctrineBaseUserRepository
