services:
  multi_user.base_user.repository:
    class: SumoCoders\FrameworkMultiUserBundle\User\DoctrineBaseUserRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - SumoCodersFrameworkMultiUserBundle:BaseUser
