multi_user_login:
    defaults: { _controller: multi_user.login.controller:loginAction }
    path: /login

multi_user_logout:
    path: /logout

multi_user_reset_password:
    defaults: { _controller: SumoCodersFrameworkMultiUserBundle:PasswordReset:reset }
    path:   /reset-password

multi_user_request_password:
    defaults: { _controller: SumoCodersFrameworkMultiUserBundle:PasswordReset:request }
    path:   /request-password