multi_user_login:
    defaults: { _controller: multi_user.login.controller:loginAction }
    path: /login

multi_user_logout:
    path: /logout

multi_user_reset_password:
    defaults: { _controller: SumoCodersFrameworkMultiUserBundle:PasswordReset:reset }
    path:   /reset-password/{token}

multi_user_request_password:
    defaults: { _controller: multi_user.password_reset.request_controller:requestAction }
    path:   /request-password-reset
