services:
  sumocoders.form_authenticator:
    class: SumoCoders\FrameworkMultiUserBundle\Security\FormAuthenticator
    arguments:
      - "@security.password_encoder"
      - "@router"
      - "@session.flash_bag"
      - "@translator.default"
      - "%sumo_coders_framework_multi_user.redirect_routes%"

  password_reset_token_created_listener:
    class: SumoCoders\FrameworkMultiUserBundle\Event\OnPasswordResetTokenCreated
    arguments:
      - "@swiftmailer.mailer"
      - "@translator.default"
      - "@templating"
      - "%mailer.default_sender_email%"
    tags:
      - { name: kernel.event_listener, event: multi_user.event.password_reset_token_created, method: onPasswordResetTokenCreated }

  password_request_token_param_converter:
    class: SumoCoders\FrameworkMultiUserBundle\Request\PasswordRequestTokenConverter
    tags:
     - { name: request.param_converter, converter: token, priority: 1}
