services:
  sumocoders.form_authenticator:
    class: SumoCoders\FrameworkMultiUserBundle\Security\FormAuthenticator
    arguments:
      - "@security.password_encoder"
      - "@router"
      - "%sumo_coders_framework_multi_user.redirect_routes%"

  multi_user.login.controller:
    class: SumoCoders\FrameworkMultiUserBundle\Controller\LoginController
    arguments:
      - "@templating"
      - "@security.authentication_utils"

  multi_user.logout.controller:
      class: SumoCoders\FrameworkMultiUserBundle\Controller\LogoutController
      arguments:
        - "@security.context"
        - "@router"
