services:
  sumocoders.form_authenticator:
    class: SumoCoders\FrameworkMultiUserBundle\Security\FormAuthenticator
    arguments:
      - "@security.password_encoder"
      - "@router"
      - "@session.flash_bag"
      - "@translator.default"
      - "%sumo_coders_framework_multi_user.redirect_routes%"
