services:
  sumocoders.form_authenticator:
    class: SumoCoders\FrameworkMultiUserBundle\Security\FormAuthenticator
    arguments:
      - "@security.password_encoder"
      - "@router"
      - "%sumo_coders_framework_multi_user.redirect_routes%"

  multi_user.login.controller:
    class: SumoCoders\FrameworkMultiUserBundle\Controller\LoginController
    arguments:
      - "@templating"
      - "@security.authentication_utils"

  multi_user.handler.request_password:
      class: SumoCoders\FrameworkMultiUserBundle\Command\RequestPasswordResetHandler
      arguments:
        - "@multi_user.user_repository.collection"
        - "@event_dispatcher"

  multi_user.handler.reset_password:
      class: SumoCoders\FrameworkMultiUserBundle\Command\ResetPasswordHandler
      arguments:
        - "@multi_user.user_repository.collection"
