services:
  sumocoders.form_authenticator:
    class: SumoCoders\FrameworkMultiUserBundle\Security\FormAuthenticator
    arguments:
      - "@security.password_encoder"
      - "@router"

  multi_user.login.controller:
    class: SumoCoders\FrameworkMultiUserBundle\Controller\LoginController
    arguments:
      - "@templating"
      - "@security.authentication_utils"
